"""Add description to version

Revision ID: 12416cd7a854
Revises: da663b733691
Create Date: 2023-03-05 18:24:37.565687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12416cd7a854'
down_revision = 'da663b733691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_versions', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('script_versions', 'version_number',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('script_versions', 'version_number',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('script_versions', 'description')
    # ### end Alembic commands ###
