"""Add 'name' and 'approved_at' columns to script submissions

Revision ID: 1632a9dd7e7b
Revises: 755fd2fc28fc
Create Date: 2023-03-08 06:27:45.813343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1632a9dd7e7b'
down_revision = '755fd2fc28fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_submissions', sa.Column('name', sa.String(), nullable=True))
    op.add_column('script_submissions', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_submissions', 'approved_at')
    op.drop_column('script_submissions', 'name')
    # ### end Alembic commands ###
