"""Create default version for script

Revision ID: 54f58e685f7b
Revises: 578e09b69441
Create Date: 2023-03-06 19:40:53.515384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f58e685f7b'
down_revision = '578e09b69441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mirc_scripts', sa.Column('default_version_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'mirc_scripts', ['default_version_id'])
    op.create_foreign_key(None, 'mirc_scripts', 'script_versions', ['default_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mirc_scripts', type_='foreignkey')
    op.drop_constraint(None, 'mirc_scripts', type_='unique')
    op.drop_column('mirc_scripts', 'default_version_id')
    # ### end Alembic commands ###
