"""Add download count to scripts

Revision ID: 578e09b69441
Revises: 7ef60e29f6a8
Create Date: 2023-03-05 18:46:42.204095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578e09b69441'
down_revision = '7ef60e29f6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mirc_scripts', sa.Column('download_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mirc_scripts', 'download_count')
    # ### end Alembic commands ###
