"""Add 'created at' column to script submission

Revision ID: 755fd2fc28fc
Revises: d210e843c621
Create Date: 2023-03-07 19:52:04.414842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755fd2fc28fc'
down_revision = 'd210e843c621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_submissions', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_submissions', 'created_at')
    # ### end Alembic commands ###
