"""Add download URL to script version

Revision ID: 7ef60e29f6a8
Revises: 12416cd7a854
Create Date: 2023-03-05 18:39:57.651003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef60e29f6a8'
down_revision = '12416cd7a854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_versions', sa.Column('download_url', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_versions', 'download_url')
    # ### end Alembic commands ###
