"""Create script submission table and submitter column for script version

Revision ID: d210e843c621
Revises: 54f58e685f7b
Create Date: 2023-03-07 19:35:16.079678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd210e843c621'
down_revision = '54f58e685f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('script_version', sa.String(), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('upload_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('script_versions', sa.Column('submitter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_versions', 'submitter')
    op.drop_table('script_submissions')
    # ### end Alembic commands ###
