"""Update cascade deletes

Revision ID: da663b733691
Revises: e39770c67ffd
Create Date: 2023-03-05 12:29:07.101879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da663b733691'
down_revision = 'e39770c67ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mirc_scripts_author_id_fkey', 'mirc_scripts', type_='foreignkey')
    op.create_foreign_key(None, 'mirc_scripts', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('script_versions_script_id_fkey', 'script_versions', type_='foreignkey')
    op.create_foreign_key(None, 'script_versions', 'mirc_scripts', ['script_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'script_versions', type_='foreignkey')
    op.create_foreign_key('script_versions_script_id_fkey', 'script_versions', 'mirc_scripts', ['script_id'], ['id'])
    op.drop_constraint(None, 'mirc_scripts', type_='foreignkey')
    op.create_foreign_key('mirc_scripts_author_id_fkey', 'mirc_scripts', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
