"""Rename, add column to script submissions table

Revision ID: f2d8de288d4e
Revises: 1632a9dd7e7b
Create Date: 2023-03-08 06:30:03.557961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d8de288d4e'
down_revision = '1632a9dd7e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_submissions', sa.Column('version', sa.String(), nullable=True))
    op.add_column('script_submissions', sa.Column('submitter', sa.String(), nullable=True))
    op.drop_column('script_submissions', 'script_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_submissions', sa.Column('script_version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('script_submissions', 'submitter')
    op.drop_column('script_submissions', 'version')
    # ### end Alembic commands ###
